// @ts-nocheck
/**
 * FontAwesomePack.ts
 *
 * Registers "Font Awesome" (Free Solid style) as a second icon pack for
 * IconLibrary.ts, alongside the default Material Symbols pack (see
 * MaterialSymbolsPack.ts) -- the Icon tool's picker automatically grows a
 * pack-selector tab once more than one pack is registered (IconTool.ts's
 * renderPickerPanel()), so this file is the entire integration surface.
 *
 * Icon geometry comes straight from the official @fortawesome/free-solid-svg-icons
 * npm package's own data (installed as a real dependency, see package.json)
 * instead of hand-copied SVG path strings -- avoids transcription errors and
 * stays in sync with upstream. Each icon sets its OWN `viewBox` (its
 * natural width/height, e.g. "0 0 576 512") rather than relying on the
 * pack-level default: unlike Material Symbols' fixed 960x960 grid, Font
 * Awesome glyphs have varying natural widths, so a single shared viewBox
 * would stretch or crop most of them (see IconLibrary.ts's own comment on
 * per-icon `viewBox`).
 *
 * Curated subset (~180 icons) rather than the full ~2000-icon set that
 * ships in the npm package -- mirrors MaterialSymbolsPack.ts's own category
 * list/scale so both packs feel consistent in the picker, and named imports
 * keep the bundle tree-shaken down to only the icons actually used here.
 */
import { IconLibrary } from '../IconLibrary.js';
import {
    faAlarmClock,
    faAnchor,
    faAppleWhole,
    faArrowDown,
    faArrowLeft,
    faArrowRight,
    faArrowRightArrowLeft,
    faArrowUp,
    faArrowUpRightFromSquare,
    faArrowsRotate,
    faAt,
    faAward,
    faBagShopping,
    faBatteryFull,
    faBell,
    faBicycle,
    faBolt,
    faBook,
    faBookOpen,
    faBookmark,
    faBreadSlice,
    faBriefcase,
    faBuilding,
    faBuildingColumns,
    faBullhorn,
    faBurger,
    faBus,
    faCakeCandles,
    faCalendar,
    faCalendarDays,
    faCamera,
    faCar,
    faCarrot,
    faCat,
    faChalkboard,
    faChampagneGlasses,
    faChartLine,
    faChartPie,
    faCheck,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faChild,
    faCircle,
    faCircleInfo,
    faCircleQuestion,
    faClock,
    faCloud,
    faCloudRain,
    faCode,
    faCoins,
    faComment,
    faComments,
    faCompass,
    faCookie,
    faCreditCard,
    faCrown,
    faDatabase,
    faDesktop,
    faDog,
    faDove,
    faDrum,
    faDrumstickBite,
    faDumbbell,
    faEnvelope,
    faEye,
    faEyeSlash,
    faFaceLaugh,
    faFaceSmile,
    faFeather,
    faFilm,
    faFireBurner,
    faFish,
    faFlag,
    faGasPump,
    faGear,
    faGem,
    faGift,
    faGlobe,
    faGraduationCap,
    faGuitar,
    faHandsClapping,
    faHandshake,
    faHashtag,
    faHeadphones,
    faHeart,
    faHeartPulse,
    faHospital,
    faHotel,
    faHourglass,
    faHouse,
    faIceCream,
    faImage,
    faKey,
    faKeyboard,
    faLaptop,
    faLeaf,
    faLightbulb,
    faLocationDot,
    faLock,
    faMagnifyingGlass,
    faMap,
    faMapPin,
    faMasksTheater,
    faMicrochip,
    faMicrophone,
    faMinus,
    faMobileScreen,
    faMoneyBill,
    faMoon,
    faMotorcycle,
    faMountain,
    faMouse,
    faMugSaucer,
    faMusic,
    faPaperPlane,
    faPause,
    faPaw,
    faPen,
    faPencil,
    faPersonWalking,
    faPhone,
    faPhoneVolume,
    faPhotoFilm,
    faPills,
    faPizzaSlice,
    faPlane,
    faPlay,
    faPlus,
    faPodcast,
    faRainbow,
    faRepeat,
    faRobot,
    faRocket,
    faRunning,
    faSchool,
    faSeedling,
    faServer,
    faShareNodes,
    faShip,
    faShuffle,
    faSmog,
    faSnowflake,
    faSquare,
    faStar,
    faStethoscope,
    faStopwatch,
    faStore,
    faSun,
    faSyringe,
    faTaxi,
    faTemperatureHigh,
    faThumbsDown,
    faThumbsUp,
    faTicket,
    faTooth,
    faTrain,
    faTrash,
    faTree,
    faTriangleExclamation,
    faTrophy,
    faTruck,
    faTv,
    faUmbrella,
    faUnlock,
    faUser,
    faUserGroup,
    faUsers,
    faUtensils,
    faVideo,
    faVolumeHigh,
    faWandMagicSparkles,
    faWater,
    faWifi,
    faWind,
    faWineGlass,
    faXmark,
} from '@fortawesome/free-solid-svg-icons';

const FONT_AWESOME_CATEGORIES = [
    { id: "geral", label: "Geral" },
    { id: "setas", label: "Setas" },
    { id: "comunicacao", label: "Comunicação" },
    { id: "festa", label: "Festa" },
    { id: "natureza", label: "Natureza" },
    { id: "alimentacao", label: "Alimentação" },
    { id: "tecnologia", label: "Tecnologia" },
    { id: "clima", label: "Clima" },
    { id: "transporte", label: "Transporte" },
    { id: "midia", label: "Mídia" },
    { id: "tempo", label: "Tempo" },
    { id: "local", label: "Local" },
    { id: "pessoas", label: "Pessoas" },
    { id: "negocios", label: "Negócios" },
    { id: "saude", label: "Saúde" },
    { id: "educacao", label: "Educação" },
];

const RAW = [
    { id: "star", category: "geral", label: "Estrela", keywords: ["favorito", "avaliação"], icon: faStar },
    { id: "heart", category: "geral", label: "Coração", keywords: ["amor", "curtir"], icon: faHeart },
    { id: "thumbs-up", category: "geral", label: "Joinha", keywords: ["curtir", "positivo"], icon: faThumbsUp },
    { id: "thumbs-down", category: "geral", label: "Joinha para baixo", keywords: ["negativo"], icon: faThumbsDown },
    { id: "check", category: "geral", label: "Check", keywords: ["ok", "confirmar"], icon: faCheck },
    { id: "xmark", category: "geral", label: "X", keywords: ["fechar", "cancelar"], icon: faXmark },
    { id: "plus", category: "geral", label: "Mais", keywords: ["adicionar"], icon: faPlus },
    { id: "minus", category: "geral", label: "Menos", keywords: ["remover"], icon: faMinus },
    { id: "circle", category: "geral", label: "Círculo", keywords: ["forma"], icon: faCircle },
    { id: "square", category: "geral", label: "Quadrado", keywords: ["forma"], icon: faSquare },
    { id: "triangle-exclamation", category: "geral", label: "Alerta", keywords: ["atenção", "aviso"], icon: faTriangleExclamation },
    { id: "circle-info", category: "geral", label: "Informação", keywords: ["info"], icon: faCircleInfo },
    { id: "circle-question", category: "geral", label: "Dúvida", keywords: ["ajuda", "pergunta"], icon: faCircleQuestion },
    { id: "bookmark", category: "geral", label: "Favorito", keywords: ["salvar", "marcador"], icon: faBookmark },
    { id: "flag", category: "geral", label: "Bandeira", keywords: ["marcar", "destaque"], icon: faFlag },
    { id: "bell", category: "geral", label: "Sino", keywords: ["notificação", "alarme"], icon: faBell },
    { id: "lightbulb", category: "geral", label: "Lâmpada", keywords: ["ideia", "luz"], icon: faLightbulb },
    { id: "key", category: "geral", label: "Chave", keywords: ["acesso", "senha"], icon: faKey },
    { id: "lock", category: "geral", label: "Cadeado", keywords: ["seguro", "privado"], icon: faLock },
    { id: "unlock", category: "geral", label: "Cadeado aberto", keywords: ["desbloquear"], icon: faUnlock },
    { id: "magnifying-glass", category: "geral", label: "Lupa", keywords: ["buscar", "pesquisar"], icon: faMagnifyingGlass },
    { id: "gear", category: "geral", label: "Engrenagem", keywords: ["configurações", "ajustes"], icon: faGear },
    { id: "trash", category: "geral", label: "Lixeira", keywords: ["excluir", "apagar"], icon: faTrash },
    { id: "pen", category: "geral", label: "Caneta", keywords: ["editar", "escrever"], icon: faPen },
    { id: "eye", category: "geral", label: "Olho", keywords: ["visualizar", "ver"], icon: faEye },
    { id: "eye-slash", category: "geral", label: "Olho fechado", keywords: ["ocultar"], icon: faEyeSlash },
    { id: "arrow-up", category: "setas", label: "Seta para cima", keywords: [], icon: faArrowUp },
    { id: "arrow-down", category: "setas", label: "Seta para baixo", keywords: [], icon: faArrowDown },
    { id: "arrow-left", category: "setas", label: "Seta para esquerda", keywords: [], icon: faArrowLeft },
    { id: "arrow-right", category: "setas", label: "Seta para direita", keywords: [], icon: faArrowRight },
    { id: "arrow-up-right-from-square", category: "setas", label: "Abrir link", keywords: ["externo"], icon: faArrowUpRightFromSquare },
    { id: "chevron-up", category: "setas", label: "Chevron cima", keywords: [], icon: faChevronUp },
    { id: "chevron-down", category: "setas", label: "Chevron baixo", keywords: [], icon: faChevronDown },
    { id: "chevron-left", category: "setas", label: "Chevron esquerda", keywords: [], icon: faChevronLeft },
    { id: "chevron-right", category: "setas", label: "Chevron direita", keywords: [], icon: faChevronRight },
    { id: "arrows-rotate", category: "setas", label: "Atualizar", keywords: ["sincronizar", "refresh"], icon: faArrowsRotate },
    { id: "arrow-right-arrow-left", category: "setas", label: "Trocar", keywords: ["alternar"], icon: faArrowRightArrowLeft },
    { id: "shuffle", category: "setas", label: "Aleatório", keywords: ["embaralhar"], icon: faShuffle },
    { id: "repeat", category: "setas", label: "Repetir", keywords: ["loop"], icon: faRepeat },
    { id: "envelope", category: "comunicacao", label: "Envelope", keywords: ["email", "carta"], icon: faEnvelope },
    { id: "phone", category: "comunicacao", label: "Telefone", keywords: ["ligar"], icon: faPhone },
    { id: "comment", category: "comunicacao", label: "Comentário", keywords: ["balão", "fala"], icon: faComment },
    { id: "comments", category: "comunicacao", label: "Conversa", keywords: ["chat"], icon: faComments },
    { id: "paper-plane", category: "comunicacao", label: "Enviar", keywords: ["avião de papel"], icon: faPaperPlane },
    { id: "share-nodes", category: "comunicacao", label: "Compartilhar", keywords: [], icon: faShareNodes },
    { id: "at", category: "comunicacao", label: "Arroba", keywords: ["email"], icon: faAt },
    { id: "hashtag", category: "comunicacao", label: "Hashtag", keywords: [], icon: faHashtag },
    { id: "microphone", category: "comunicacao", label: "Microfone", keywords: ["áudio", "gravar"], icon: faMicrophone },
    { id: "video", category: "comunicacao", label: "Vídeo", keywords: ["câmera"], icon: faVideo },
    { id: "phone-volume", category: "comunicacao", label: "Chamada", keywords: [], icon: faPhoneVolume },
    { id: "bullhorn", category: "comunicacao", label: "Megafone", keywords: ["anúncio"], icon: faBullhorn },
    { id: "gift", category: "festa", label: "Presente", keywords: ["aniversário"], icon: faGift },
    { id: "cake-candles", category: "festa", label: "Bolo", keywords: ["aniversário", "festa"], icon: faCakeCandles },
    { id: "champagne-glasses", category: "festa", label: "Brinde", keywords: ["celebração"], icon: faChampagneGlasses },
    { id: "masks-theater", category: "festa", label: "Teatro", keywords: ["máscaras"], icon: faMasksTheater },
    { id: "music", category: "festa", label: "Música", keywords: ["nota musical"], icon: faMusic },
    { id: "drum", category: "festa", label: "Tambor", keywords: ["instrumento"], icon: faDrum },
    { id: "guitar", category: "festa", label: "Violão", keywords: ["instrumento"], icon: faGuitar },
    { id: "ticket", category: "festa", label: "Ingresso", keywords: ["bilhete"], icon: faTicket },
    { id: "crown", category: "festa", label: "Coroa", keywords: ["realeza"], icon: faCrown },
    { id: "gem", category: "festa", label: "Joia", keywords: ["diamante"], icon: faGem },
    { id: "wand-magic-sparkles", category: "festa", label: "Varinha mágica", keywords: ["magia"], icon: faWandMagicSparkles },
    { id: "leaf", category: "natureza", label: "Folha", keywords: ["planta"], icon: faLeaf },
    { id: "tree", category: "natureza", label: "Árvore", keywords: [], icon: faTree },
    { id: "seedling", category: "natureza", label: "Muda", keywords: ["broto", "planta"], icon: faSeedling },
    { id: "paw", category: "natureza", label: "Pata", keywords: ["animal"], icon: faPaw },
    { id: "feather", category: "natureza", label: "Pena", keywords: [], icon: faFeather },
    { id: "fish", category: "natureza", label: "Peixe", keywords: [], icon: faFish },
    { id: "dove", category: "natureza", label: "Pomba", keywords: ["paz"], icon: faDove },
    { id: "sun", category: "natureza", label: "Sol", keywords: [], icon: faSun },
    { id: "moon", category: "natureza", label: "Lua", keywords: [], icon: faMoon },
    { id: "cloud", category: "natureza", label: "Nuvem", keywords: [], icon: faCloud },
    { id: "mountain", category: "natureza", label: "Montanha", keywords: [], icon: faMountain },
    { id: "water", category: "natureza", label: "Água", keywords: [], icon: faWater },
    { id: "dog", category: "natureza", label: "Cachorro", keywords: ["animal", "pet"], icon: faDog },
    { id: "cat", category: "natureza", label: "Gato", keywords: ["animal", "pet"], icon: faCat },
    { id: "pizza-slice", category: "alimentacao", label: "Pizza", keywords: [], icon: faPizzaSlice },
    { id: "burger", category: "alimentacao", label: "Hambúrguer", keywords: [], icon: faBurger },
    { id: "ice-cream", category: "alimentacao", label: "Sorvete", keywords: [], icon: faIceCream },
    { id: "mug-saucer", category: "alimentacao", label: "Café", keywords: ["xícara"], icon: faMugSaucer },
    { id: "apple-whole", category: "alimentacao", label: "Maçã", keywords: ["fruta"], icon: faAppleWhole },
    { id: "carrot", category: "alimentacao", label: "Cenoura", keywords: ["legume"], icon: faCarrot },
    { id: "bread-slice", category: "alimentacao", label: "Pão", keywords: [], icon: faBreadSlice },
    { id: "cookie", category: "alimentacao", label: "Biscoito", keywords: [], icon: faCookie },
    { id: "wine-glass", category: "alimentacao", label: "Taça de vinho", keywords: ["bebida"], icon: faWineGlass },
    { id: "utensils", category: "alimentacao", label: "Talheres", keywords: ["comida"], icon: faUtensils },
    { id: "fire-burner", category: "alimentacao", label: "Fogão", keywords: ["cozinhar"], icon: faFireBurner },
    { id: "drumstick-bite", category: "alimentacao", label: "Coxa de frango", keywords: ["carne"], icon: faDrumstickBite },
    { id: "laptop", category: "tecnologia", label: "Notebook", keywords: ["computador"], icon: faLaptop },
    { id: "mobile-screen", category: "tecnologia", label: "Celular", keywords: ["smartphone"], icon: faMobileScreen },
    { id: "desktop", category: "tecnologia", label: "Computador", keywords: ["desktop"], icon: faDesktop },
    { id: "keyboard", category: "tecnologia", label: "Teclado", keywords: [], icon: faKeyboard },
    { id: "mouse", category: "tecnologia", label: "Mouse", keywords: [], icon: faMouse },
    { id: "wifi", category: "tecnologia", label: "Wi-Fi", keywords: ["internet"], icon: faWifi },
    { id: "database", category: "tecnologia", label: "Banco de dados", keywords: [], icon: faDatabase },
    { id: "server", category: "tecnologia", label: "Servidor", keywords: [], icon: faServer },
    { id: "code", category: "tecnologia", label: "Código", keywords: ["programação"], icon: faCode },
    { id: "robot", category: "tecnologia", label: "Robô", keywords: ["ia"], icon: faRobot },
    { id: "microchip", category: "tecnologia", label: "Chip", keywords: ["processador"], icon: faMicrochip },
    { id: "battery-full", category: "tecnologia", label: "Bateria", keywords: [], icon: faBatteryFull },
    { id: "snowflake", category: "clima", label: "Floco de neve", keywords: ["inverno", "frio"], icon: faSnowflake },
    { id: "umbrella", category: "clima", label: "Guarda-chuva", keywords: ["chuva"], icon: faUmbrella },
    { id: "bolt", category: "clima", label: "Raio", keywords: ["tempestade"], icon: faBolt },
    { id: "temperature-high", category: "clima", label: "Temperatura alta", keywords: ["calor"], icon: faTemperatureHigh },
    { id: "smog", category: "clima", label: "Neblina", keywords: [], icon: faSmog },
    { id: "rainbow", category: "clima", label: "Arco-íris", keywords: [], icon: faRainbow },
    { id: "wind", category: "clima", label: "Vento", keywords: [], icon: faWind },
    { id: "cloud-rain", category: "clima", label: "Chuva", keywords: [], icon: faCloudRain },
    { id: "car", category: "transporte", label: "Carro", keywords: [], icon: faCar },
    { id: "plane", category: "transporte", label: "Avião", keywords: ["viagem"], icon: faPlane },
    { id: "train", category: "transporte", label: "Trem", keywords: [], icon: faTrain },
    { id: "ship", category: "transporte", label: "Navio", keywords: [], icon: faShip },
    { id: "bicycle", category: "transporte", label: "Bicicleta", keywords: [], icon: faBicycle },
    { id: "bus", category: "transporte", label: "Ônibus", keywords: [], icon: faBus },
    { id: "taxi", category: "transporte", label: "Táxi", keywords: [], icon: faTaxi },
    { id: "gas-pump", category: "transporte", label: "Posto de gasolina", keywords: ["combustível"], icon: faGasPump },
    { id: "motorcycle", category: "transporte", label: "Moto", keywords: [], icon: faMotorcycle },
    { id: "truck", category: "transporte", label: "Caminhão", keywords: [], icon: faTruck },
    { id: "anchor", category: "transporte", label: "Âncora", keywords: ["náutico"], icon: faAnchor },
    { id: "rocket", category: "transporte", label: "Foguete", keywords: ["espaço"], icon: faRocket },
    { id: "image", category: "midia", label: "Imagem", keywords: ["foto"], icon: faImage },
    { id: "camera", category: "midia", label: "Câmera", keywords: [], icon: faCamera },
    { id: "film", category: "midia", label: "Filme", keywords: ["cinema"], icon: faFilm },
    { id: "photo-film", category: "midia", label: "Mídia", keywords: ["foto e vídeo"], icon: faPhotoFilm },
    { id: "play", category: "midia", label: "Play", keywords: ["reproduzir"], icon: faPlay },
    { id: "pause", category: "midia", label: "Pausa", keywords: [], icon: faPause },
    { id: "volume-high", category: "midia", label: "Volume", keywords: ["som"], icon: faVolumeHigh },
    { id: "headphones", category: "midia", label: "Fones de ouvido", keywords: [], icon: faHeadphones },
    { id: "podcast", category: "midia", label: "Podcast", keywords: [], icon: faPodcast },
    { id: "tv", category: "midia", label: "TV", keywords: ["televisão"], icon: faTv },
    { id: "clock", category: "tempo", label: "Relógio", keywords: ["hora"], icon: faClock },
    { id: "calendar", category: "tempo", label: "Calendário", keywords: ["data"], icon: faCalendar },
    { id: "calendar-days", category: "tempo", label: "Calendário de dias", keywords: ["agenda"], icon: faCalendarDays },
    { id: "hourglass", category: "tempo", label: "Ampulheta", keywords: ["tempo passando"], icon: faHourglass },
    { id: "stopwatch", category: "tempo", label: "Cronômetro", keywords: [], icon: faStopwatch },
    { id: "alarm-clock", category: "tempo", label: "Despertador", keywords: [], icon: faAlarmClock },
    { id: "location-dot", category: "local", label: "Localização", keywords: ["pin", "mapa"], icon: faLocationDot },
    { id: "map-pin", category: "local", label: "Alfinete de mapa", keywords: [], icon: faMapPin },
    { id: "map", category: "local", label: "Mapa", keywords: [], icon: faMap },
    { id: "compass", category: "local", label: "Bússola", keywords: ["direção"], icon: faCompass },
    { id: "globe", category: "local", label: "Globo", keywords: ["mundo"], icon: faGlobe },
    { id: "house", category: "local", label: "Casa", keywords: ["residência"], icon: faHouse },
    { id: "building", category: "local", label: "Prédio", keywords: ["edifício"], icon: faBuilding },
    { id: "school", category: "local", label: "Escola", keywords: [], icon: faSchool },
    { id: "hotel", category: "local", label: "Hotel", keywords: [], icon: faHotel },
    { id: "user", category: "pessoas", label: "Usuário", keywords: ["pessoa"], icon: faUser },
    { id: "users", category: "pessoas", label: "Usuários", keywords: ["grupo"], icon: faUsers },
    { id: "user-group", category: "pessoas", label: "Grupo de pessoas", keywords: ["equipe"], icon: faUserGroup },
    { id: "child", category: "pessoas", label: "Criança", keywords: [], icon: faChild },
    { id: "person-walking", category: "pessoas", label: "Pessoa caminhando", keywords: [], icon: faPersonWalking },
    { id: "face-smile", category: "pessoas", label: "Rosto sorrindo", keywords: ["feliz"], icon: faFaceSmile },
    { id: "face-laugh", category: "pessoas", label: "Rosto rindo", keywords: [], icon: faFaceLaugh },
    { id: "handshake", category: "pessoas", label: "Aperto de mãos", keywords: ["acordo"], icon: faHandshake },
    { id: "hands-clapping", category: "pessoas", label: "Aplausos", keywords: ["palmas"], icon: faHandsClapping },
    { id: "briefcase", category: "negocios", label: "Pasta executiva", keywords: ["trabalho"], icon: faBriefcase },
    { id: "chart-line", category: "negocios", label: "Gráfico de linha", keywords: ["crescimento"], icon: faChartLine },
    { id: "chart-pie", category: "negocios", label: "Gráfico de pizza", keywords: [], icon: faChartPie },
    { id: "money-bill", category: "negocios", label: "Dinheiro", keywords: [], icon: faMoneyBill },
    { id: "coins", category: "negocios", label: "Moedas", keywords: [], icon: faCoins },
    { id: "credit-card", category: "negocios", label: "Cartão de crédito", keywords: [], icon: faCreditCard },
    { id: "bag-shopping", category: "negocios", label: "Sacola de compras", keywords: [], icon: faBagShopping },
    { id: "store", category: "negocios", label: "Loja", keywords: [], icon: faStore },
    { id: "building-columns", category: "negocios", label: "Banco", keywords: ["instituição"], icon: faBuildingColumns },
    { id: "heart-pulse", category: "saude", label: "Batimento cardíaco", keywords: [], icon: faHeartPulse },
    { id: "stethoscope", category: "saude", label: "Estetoscópio", keywords: ["médico"], icon: faStethoscope },
    { id: "pills", category: "saude", label: "Comprimidos", keywords: ["remédio"], icon: faPills },
    { id: "syringe", category: "saude", label: "Seringa", keywords: ["vacina"], icon: faSyringe },
    { id: "hospital", category: "saude", label: "Hospital", keywords: [], icon: faHospital },
    { id: "tooth", category: "saude", label: "Dente", keywords: ["dentista"], icon: faTooth },
    { id: "dumbbell", category: "saude", label: "Halter", keywords: ["academia"], icon: faDumbbell },
    { id: "running", category: "saude", label: "Corrida", keywords: ["exercício"], icon: faRunning },
    { id: "graduation-cap", category: "educacao", label: "Capelo", keywords: ["formatura"], icon: faGraduationCap },
    { id: "book", category: "educacao", label: "Livro", keywords: [], icon: faBook },
    { id: "book-open", category: "educacao", label: "Livro aberto", keywords: ["leitura"], icon: faBookOpen },
    { id: "pencil", category: "educacao", label: "Lápis", keywords: ["escrever"], icon: faPencil },
    { id: "chalkboard", category: "educacao", label: "Quadro-negro", keywords: ["aula"], icon: faChalkboard },
    { id: "award", category: "educacao", label: "Prêmio", keywords: ["medalha"], icon: faAward },
    { id: "trophy", category: "educacao", label: "Troféu", keywords: ["vitória"], icon: faTrophy },
];

const FONT_AWESOME_ICONS = RAW.map(({ id, category, label, keywords, icon }) => ({
    id,
    category,
    label,
    keywords,
    viewBox: `0 0 ${icon.icon[0]} ${icon.icon[1]}`,
    paths: [icon.icon[4]],
}));

IconLibrary.registerPack("font-awesome", {
    label: "Font Awesome",
    viewBox: "0 0 512 512", // fallback only -- every icon above sets its own
    categories: FONT_AWESOME_CATEGORIES,
    icons: FONT_AWESOME_ICONS,
});
